# Generated by Django 5.0.14 on 2026-05-30 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Olympiad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("year", models.PositiveIntegerField(verbose_name="Год проведения")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дедлайн регистрации"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Место проведения"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Уровень"
                    ),
                ),
                (
                    "regulation_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="regulations/",
                        verbose_name="Положение",
                    ),
                ),
                (
                    "tasks_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tasks/",
                        verbose_name="Задания прошлых лет",
                    ),
                ),
                (
                    "responsible_teacher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_olympiads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Олимпиада",
                "verbose_name_plural": "Олимпиады",
                "ordering": ["-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название бланка"),
                ),
                (
                    "cert_type",
                    models.CharField(
                        choices=[
                            ("diploma", "Грамота"),
                            ("certificate", "Сертификат"),
                            ("degree", "Диплом"),
                        ],
                        default="certificate",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="Файл бланка",
                    ),
                ),
                (
                    "olympiad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="olympiads.olympiad",
                        verbose_name="Олимпиада",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бланк сертификата/грамоты",
                "verbose_name_plural": "Бланки сертификатов/грамот",
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Формируется"),
                            ("prepared", "Подготовлен"),
                            ("published", "Опубликован"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "olympiad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols",
                        to="olympiads.olympiad",
                        verbose_name="Олимпиада",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_protocols",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Протокол",
                "verbose_name_plural": "Протоколы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="Баллы")),
                (
                    "place",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Место"
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("winner", "Победитель"),
                            ("prize_winner", "Призёр"),
                            ("participant", "Участник"),
                        ],
                        default="participant",
                        max_length=20,
                        verbose_name="Тип результата",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="olympiads.protocol",
                        verbose_name="Протокол",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат",
                "verbose_name_plural": "Результаты",
                "ordering": ["place", "-score"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата записи"),
                ),
                (
                    "olympiad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="olympiads.olympiad",
                        verbose_name="Олимпиада",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на олимпиаду",
                "verbose_name_plural": "Записи на олимпиады",
                "unique_together": {("olympiad", "student")},
            },
        ),
    ]
